version: '3.8'

services:
  catalogdb:
    image: postgres
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  # Uncomment this section only when you want to run catalogapi
  catalogapi:
    build:
      context: ./Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - catalogdb
